"""add setup state

Revision ID: 561b924be9e7
Revises: 77c82d7f11f8
Create Date: 2026-05-18 16:00:38.334571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561b924be9e7'
down_revision: Union[str, Sequence[str], None] = '77c82d7f11f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state in ('not_started', 'in_progress', 'ready_to_apply', 'applying', 'completed', 'failed', 'locked', 'reconfigure_mode')", name='ck_setup_state_state'),
    sa.CheckConstraint('version >= 1', name='ck_setup_state_version'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_state_state'), 'setup_state', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setup_state_state'), table_name='setup_state')
    op.drop_table('setup_state')
    # ### end Alembic commands ###
