"""add oidc signing keys

Revision ID: 6c2f4c9d1a7e
Revises: dad11091fd15
Create Date: 2026-05-13 16:28:29.505870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2f4c9d1a7e'
down_revision: Union[str, Sequence[str], None] = 'dad11091fd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_signing_key_audit_events',
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('kid', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_signing_key_audit_events_event'), 'oidc_signing_key_audit_events', ['event'], unique=False)
    op.create_index(op.f('ix_oidc_signing_key_audit_events_kid'), 'oidc_signing_key_audit_events', ['kid'], unique=False)
    op.create_table('oidc_signing_keys',
    sa.Column('kid', sa.String(), nullable=False),
    sa.Column('public_jwk', sa.Text(), nullable=False),
    sa.Column('private_jwk_encrypted', sa.Text(), nullable=False),
    sa.Column('alg', sa.String(), nullable=False),
    sa.Column('kty', sa.String(), nullable=False),
    sa.Column('use', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('backend_reference', sa.String(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validating_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_signing_keys_kid'), 'oidc_signing_keys', ['kid'], unique=True)
    op.create_index(op.f('ix_oidc_signing_keys_status'), 'oidc_signing_keys', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oidc_signing_keys_status'), table_name='oidc_signing_keys')
    op.drop_index(op.f('ix_oidc_signing_keys_kid'), table_name='oidc_signing_keys')
    op.drop_table('oidc_signing_keys')
    op.drop_index(op.f('ix_oidc_signing_key_audit_events_kid'), table_name='oidc_signing_key_audit_events')
    op.drop_index(op.f('ix_oidc_signing_key_audit_events_event'), table_name='oidc_signing_key_audit_events')
    op.drop_table('oidc_signing_key_audit_events')
    # ### end Alembic commands ###
