"""add email verification tokens

Revision ID: 77c82d7f11f8
Revises: 7f362123846e
Create Date: 2026-05-17 17:49:01.136022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c82d7f11f8'
down_revision: Union[str, Sequence[str], None] = '7f362123846e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_ip_hash', sa.String(), nullable=True),
    sa.Column('user_agent_hash', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tokens_consumed_at'), 'email_tokens', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_email_tokens_email'), 'email_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_email_tokens_expires_at'), 'email_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_tokens_purpose'), 'email_tokens', ['purpose'], unique=False)
    op.create_index('ix_email_tokens_purpose_consumed', 'email_tokens', ['purpose', 'consumed_at'], unique=False)
    op.create_index(op.f('ix_email_tokens_token_hash'), 'email_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_tokens_user_purpose_expiry', 'email_tokens', ['user_id', 'purpose', 'expires_at'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_index('ix_email_tokens_user_purpose_expiry', table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_token_hash'), table_name='email_tokens')
    op.drop_index('ix_email_tokens_purpose_consumed', table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_purpose'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_expires_at'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_email'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_consumed_at'), table_name='email_tokens')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
