"""add permission requests

Revision ID: 7f362123846e
Revises: 6c2f4c9d1a7e
Create Date: 2026-05-13 17:04:50.809854

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7f362123846e"
down_revision: Union[str, Sequence[str], None] = "6c2f4c9d1a7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PERMISSIONS_ENUM = sa.Enum(
    "ROOT",
    "ADMIN",
    "DRAW_OPERATOR",
    "DEVELOPER",
    "SUPPORT",
    name="permissionsenum",
)
PERMISSIONS_ENUM_PG = postgresql.ENUM(
    "ROOT",
    "ADMIN",
    "DRAW_OPERATOR",
    "DEVELOPER",
    "SUPPORT",
    name="permissionsenum",
    create_type=False,
)
REQUEST_STATUS_ENUM = sa.Enum(
    "PENDING",
    "APPROVED",
    "DENIED",
    "CANCELLED",
    "SUPERSEDED",
    name="permissionrequeststatusenum",
)


def _permissions_enum():
    if op.get_bind().dialect.name == "postgresql":
        return PERMISSIONS_ENUM_PG
    return PERMISSIONS_ENUM


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "ALTER TYPE permissionsenum ADD VALUE IF NOT EXISTS 'DEVELOPER'"
        )

    op.create_table(
        "permission_requests",
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("permission_type", _permissions_enum(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", REQUEST_STATUS_ENUM, nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_requests_decided_at"),
        "permission_requests",
        ["decided_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_requests_decided_by"),
        "permission_requests",
        ["decided_by"],
        unique=False,
    )
    op.create_index(
        "ix_permission_requests_one_pending_per_user_type",
        "permission_requests",
        ["requester_id", "permission_type"],
        unique=True,
        sqlite_where=sa.text("status = 'PENDING'"),
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        op.f("ix_permission_requests_permission_type"),
        "permission_requests",
        ["permission_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_requests_requester_id"),
        "permission_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_requests_status"),
        "permission_requests",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_permission_requests_status"),
        table_name="permission_requests",
    )
    op.drop_index(
        op.f("ix_permission_requests_requester_id"),
        table_name="permission_requests",
    )
    op.drop_index(
        op.f("ix_permission_requests_permission_type"),
        table_name="permission_requests",
    )
    op.drop_index(
        "ix_permission_requests_one_pending_per_user_type",
        table_name="permission_requests",
        sqlite_where=sa.text("status = 'PENDING'"),
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(
        op.f("ix_permission_requests_decided_by"),
        table_name="permission_requests",
    )
    op.drop_index(
        op.f("ix_permission_requests_decided_at"),
        table_name="permission_requests",
    )
    op.drop_table("permission_requests")
    # ### end Alembic commands ###
