"""add setup runtime settings

Revision ID: e37d8be9438a
Revises: 561b924be9e7
Create Date: 2026-05-23 11:58:58.059823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37d8be9438a'
down_revision: Union[str, Sequence[str], None] = '561b924be9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_runtime_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('secret_ref', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source in ('wizard', 'setup', 'admin_reconfigure', 'migration')", name='ck_setup_runtime_source'),
    sa.CheckConstraint('version >= 1', name='ck_setup_runtime_version'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_setup_runtime_settings_source'), 'setup_runtime_settings', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setup_runtime_settings_source'), table_name='setup_runtime_settings')
    op.drop_table('setup_runtime_settings')
    # ### end Alembic commands ###
