FROM python:3.11-alpine
ENV POETRY_VIRTUALENVS_CREATE=false
WORKDIR /app

COPY satoidc/ .

RUN pip install poetry

RUN poetry config installer.max-workers 10
RUN poetry install --no-root --no-interaction --no-ansi --without dev

EXPOSE 8000